<div class="jumbotron">
<h1>Add a meetup</h1>
<br />
<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
<?= $this->formRow($form->get('title')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('description')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('date_debut')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('date_fin')) ?>
</div>

<div class="form-group">
<?= $this->formInput($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag($form); ?>
</div>
