<div class="jumbotron">
	<a class="" href="<?= $this->url('home') ?>">
	   <button class="btn btn-default">
	    	retour menu
	   </button>
   </a>
<h1 class="titre_jumbotron">Liste de meetup</h1>

<ul class="container_meetup">
    <?php foreach ($this->meetups as $meetup): /* @var $meetup \Application\Entity\Film */ ?>
    <li class="list_meetup">
    <?php

    echo "<h3>".$meetup->getTitle()."</h3>";
    echo "<br />";
    echo "<br />";
    echo $meetup->getDescription();
     ?>

     <div class="button_view_meetup">
    
    <a href="<?= $this->url('meetup/view'); ?>?id=<?= $meetup->getId() ?>">
     <button class="btn btn-success "> voir & modifier l'evenement</button>
    </a>
     </div>
        
     </li>

    <?php endforeach; ?>
</ul>

<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>
</div>
