<div class="jumbotron">
	<a class="" href="<?= $this->url('meetup') ?>">
	   <button class="btn btn-default">
	    	retour a la liste des meetups
	   </button>
   </a>
   	<a class="" href="<?= $this->url('meetup/view'); ?>?id=<?= $meetup->getId() ?>">
	   <button class="btn btn-default">
	    	retour à ce meetup
	   </button>
   </a>
   <br />
<h1>Modifier <?= $this->meetup->getTitle() ?></h1>
<br />
<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
<?= $this->formRow($form->get('title')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('description')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('date_debut')) ?>
</div>

<div class="form-group">
<?= $this->formRow($form->get('date_fin')) ?>
</div>

<div class="form-group">
<?= $this->formInput($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag($form); ?>
</div>
