<div class="jumbotron">
    <h1 class="titre_jumbotron">Bienvenu sur mon projet zend</h1>

    <br />
    <p>On organise des supper réunion, clique sur le bouton si dessous pour voir les prochaines réunion ou peut-étre en crée une.</p>

    <div class="bouton_container">
    	<a class="" href="<?= $this->url('meetup') ?>">
   <button class="btn btn-primary bouton_meetup"> aller voir les meetups </button>
   </a>
   	</div>

</div>

